[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:streamlit]
command=python -m streamlit run streamlit_app.py --server.port 8501 --server.headless true --server.address 0.0.0.0
directory=/app/src
stdout_logfile=/var/log/supervisor/streamlit.log
stderr_logfile=/var/log/supervisor/streamlit.error.log
autorestart=true
priority=10
user=root

[program:cron]
    command=busybox crond -f -c /app/src/crontab.txt -l 2
stdout_logfile=/var/log/supervisor/cron.log
stderr_logfile=/var/log/supervisor/cron.error.log
autorestart=true
priority=20
user=root
